Server:
  Mode: debug # debug | release
  Port: :8765
  DbType: "mysql" # mysql | sqlite
  DbAutoMigrate: true # 是否自动迁移数据库表结构 (表结构没变可以不迁移, 提高启动速度)
  DbLogMode: "error" # 日志级别 silent, error, warn, info, 默认 info
JWT:
  Secret: "123456"
  Expire: 24 # hour
  Issuer: "Blog"
Mysql:
  Host: "127.0.0.1"
  Port: "3306"
  Config: "charset=utf8mb4&parseTime=True&loc=Local" # 其他配置, 例如时区
  Dbname: "gvb"
  Username: "root"
  Password: "123456"
Redis:
  DB: 7
  Addr: '127.0.0.1:6379'
  Password: ''
Session:
  Name: "mysession"
  Salt: "salt"
  MaxAge: 600 # second
Log:
  Level: "debug" # debug | info | warn | error
  Format: "text" # text | json
  Directory: "log"
Email:
  Host: "smtp.qq.com"
  Port: 465
  From: ""
  SmtpPass: ""
  SmtpUser: ""
Captcha:
  SendEmail: true
  ExpireTime: 15
Upload:
  OssType: "local"
  Path: "public/uploaded"
  StorePath: "../public/uploaded"
Qiniu:
  ImgPath: "" # 外链
  Zone: ""
  Bucket: ""
  AccessKey: ""
  SecretKey: ""
  UseHttps: false
  UseCdnDomains: false